first_project/first_app/urls.py
from django.urls import path
from first_app import views

# TEMPLATE TAGGING
app_name = 'first_app'

urlpatterns = [
    path('',views.index, name='index'),
    path('relative/',views.relative,name='relative'),
    path('other/',views.other,name='other')
]

first_project/first_project/urls.py
from django.contrib import admin
from django.urls import path
from first_app import views
from django.urls import include

urlpatterns = [
    path('', views.index, name='index'),
    path('admin/', admin.site.urls),
    path('first_app/', include('first_app.urls')),
    path('formpage/',views.form_name_view,name='form_name'),
    path('webpages/',views.webpages, name='form_name2'),
    path('relative/',views.relative,name='relative'),
    path('other/',views.other,name='other'),
    path('register/',views.register,name='register'),
    path('user_login/',views.user_login,name='user_login'),
    path('logout/',views.user_logout,name='logout'),
    path('special/',views.special,name='special'),
]

first_project/first_app/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Topic(models.Model):
    top_name = models.CharField(max_length=264, unique=True)

    def __str__(self) -> str:
        return self.top_name

class Webpage(models.Model):
    topic = models.ForeignKey(Topic, on_delete=models.DO_NOTHING)
    name = models.CharField(max_length=264, unique=True)
    url = models.URLField(unique=True)

    def __str__(self) -> str:
        return self.name

class AccessRecord(models.Model):
    name = models.ForeignKey(Webpage, on_delete=models.DO_NOTHING,)
    date = models.DateField()

    def __str__(self) -> str:
        return str(self.date)

class UserProfileInfo(models.Model):

    user = models.OneToOneField(User, on_delete=models.DO_NOTHING)

    # additional
    portfolio_site = models.URLField(blank=True)

    profile_pic = models.ImageField(upload_to='profile_pics', blank=True)

    def __str__(self) -> str:
        return self.user.username

first_project/first_app/forms.py
from django import forms
from django.contrib.auth.models import User
from django.db.models import fields
from first_app.models import UserProfileInfo

from django.core import validators

def check_for_z(value):
    if value[0].lower() != 'z':
        raise forms.ValidationError("NAME NEEDS TO START WITH Z")

class FormName(forms.Form):
    name = forms.CharField(validators=[check_for_z])
    email = forms.EmailField()
    verify_email = forms.EmailField(label='Enter your email again')
    text = forms.CharField(widget=forms.Textarea)
    botcatcher = forms.CharField(required=False, widget=forms.HiddenInput, validators=[validators.MaxLengthValidator(0)])


    def clean(self):
        all_clean_data = super().clean()
        email = all_clean_data['email']
        vmail = all_clean_data['verify_email']

        if email != vmail:
            raise forms.ValidationError("MAKE SURE EMAILS MARCH!")

from first_app.models import Webpage

class NewWebpageForm(forms.ModelForm):
    class Meta:
        model = Webpage
        fields = '__all__'


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username','email','password')

class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ('portfolio_site','profile_pic')

first_project/first_app/views.py
from django.contrib.auth.models import User
from django.forms.widgets import PasswordInput
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from first_app.models import Topic, Webpage, AccessRecord
from . import forms
from first_app.forms import NewWebpageForm, UserForm, UserProfileInfoForm

from django.contrib.auth import authenticate, login, logout
from django.urls import reverse
from django.contrib.auth.decorators import login_required

# Create your views here.
# def index(request):
#     webpages_list = AccessRecord.objects.order_by('date')
#     date_dict = {'access_records': webpages_list}
#     return render(request, 'first_app/index.html', context=date_dict)

def form_name_view(request):
    form = forms.FormName()
    if request.method == "POST":
        form = forms.FormName(request.POST)

        if form.is_valid():
            # CODE HERE
            print("Validation Success!")
            print(f"Name: {form.cleaned_data['name']}")
            print(f"Email: {form.cleaned_data['email']}")
            print(f"Text: {form.cleaned_data['text']}")

    return render(request,'first_app/form_page.html', {'form':form})

def webpages(request):
    form = NewWebpageForm()

    if request.method == "POST":
        form = NewWebpageForm(request.POST)

        if form.is_valid():
            form.save(commit=True)
            return index(request)
        else:
            print("Error Form Invalid")
    
    return render(request, 'first_app/webpages.html', {'form': form})


def index(request):
    context_dict = {'text':'hello world', 'number':100}
    return render(request, 'templates/index.html', context_dict)

    
def other(request):
    return render(request, 'templates/other.html')

    
def relative(request):
    return render(request, 'templates/relative_url_templates.html')

def index(request):
    return render(request,'user_authentication/index.html')

@login_required
def special(request):
    return HttpResponse("You are logged in, Nice!")

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

def register(request):

    registered = False

    if request.method == "POST":
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']

            profile.save()

            registered = True
        else:
            print(user_form.error, profile_form.errors)
    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()

    return render(request, 'user_authentication/registration.html', {'user_form':user_form, 'profile_form':profile_form,'registered':registered})

def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('index'))
            
            else:
                return HttpResponse("ACCOUNT NOT ACTIVE")
        else:
            print("Someone tried to login and failed!")
            print("Username:{} and password {}".format(username, password))
            return HttpResponse("invalid login details supplied!")
    else:
        return render(request, 'user_authentication/login.html',{})

first_project/templates/first_app/form_page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Forms</title>
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
</head>
<body>
    <h1>Fill out the form!</h1>
    <div class="container">
        <form action="" method="POST">
            {{form.as_p}}
            {% csrf_token %}
            <input type="submit" class="btn btn-primary" value="Submit">
        </form>
    </div>
</body>
</html>

first_project/templates/first_app/index.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>First App</title>
    <link rel="stylesheet" href="{% static "css/mystyle.css" %}"/>
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
</head>
<body>
    <h1>Welcome to home page!</h1>
    <img src="{% static "images/download.png" %}" alt="Thumb">
    <div class='djangotwo'>
        {% if access_records %}
            <table>
                <thead>
                    <th>Site Name</th>
                    <th>Date Accessed</th>
                </thead>        
                {% for acc in access_records %}
                <tr>
                    <td>
                        {{ acc.name }}
                        {{ acc.date }}
                    </td>
                </tr>
                {% endfor %}
            </table>
        {% else %}
            <p>NO ACCESS RECORDS FOUND!</p>
        {% endif %}
    </div>
    <h2>
        Go to /formpage to fill out the form
    </h2>
</body>
</html>

first_project/templates/first_app/webpages.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Webpages</title>
</head>
<body>
    <div>
        <h1>Please enter the webpage</h1>
        <form action="" method="post">
            {{ form.as_p }}
            {% csrf_token%}
            <input type="submit" name="" value="submit">
        </form>
    </div>
</body>
</html>

first_project/templates/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <title>Document</title>
</head>
<body>
    <nav class="navbar navbar-default navbar-static-top">
        <div class="container">
            <ul class="nav navbar-nav">
                <li class="navbar-brand">
                    <a href="{%url 'index'%}">BRAND</a>
                </li>
                <li class="navbar-link">
                    <a href="{%url 'admin:index'%}">Admin</a>
                </li>
                <li class="navbar-link">
                    <a href="{%url 'other'%}">Other</a>
                </li>
            </ul>
        </div>
    </nav>
    <div class="container">
        {% block body_block %}
        <!-- Anything outside of this will be inherited if you extend! -->
        {% endblock %}
    </div>
</body>
</html>

first_project/templates/templates/index.html
<!DOCTYPE html>
{% extends 'templates/base.html' %}
    {% block body_block %}
        <h1>WELCOME TO INDEX!</h1>
        <h2>This is an example of template inheritance</h2>
        <h1>{{text|cut:'hello'}}</h1>
        <h1>{{number|add:"2"}}</h1>
    {% endblock %}

first_project/templates/templates/other.html
<!DOCTYPE html>
{% extends 'templates/base.html' %}
    {% block body_block %}
        <h1>WELCOME TO OTHER!</h1>
        <h2>This is an example of template inheritance</h2>
    {% endblock %}

first_project/templates/templates/relative_url_templates.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Welcome to Relative Url Templates</h1>
    <a href="{% url 'first_app:other' %}">The other page</a>
    <a href="{% url 'admin:index'%}">Link to Admin</a>
    <a href="{% url 'index' %}">Link to Index</a>
</body>
</html>

first_project/templates/user_authentication/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <title>Document</title>
</head>
<body>
    <nav class="navbar navbar-default navbar-static-top">
        <div class="container"> 
            <ul class="nav navbar-nav">
                <li><a class="navbar-brand" href="{% url 'index' %}">DJANGO</a> </li>
                <li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a> </li>
                <li><a class="navbar-link" href="{% url 'register' %}">Register</a> </li>
                {% if user.is_authenticated %}
                    <li><a class="navbar-link" href="{% url 'logout' %}">Logout</a></li>
                {% else %}
                    <li><a class="navbar-link" href="{% url 'user_login' %}">Login</a></li>
                {% endif %}
            </ul>
        </div>
    </nav>
    <div class="container">
        {% block body_block%}
        {% endblock %}
    </div>
</body>
</html>

first_project/templates/user_authentication/index.html
{% extends "user_authentication/base.html" %}
{% block body_block %}

<div class="jumbotron">
    <h1>Index Page</h1>
</div>

{% endblock %}

first_project/templates/user_authentication/login.html
{% extends "user_authentication/base.html" %}
{% block body_block %}

<div>
    <h1>Please Login</h1>
    <form action="{% url 'user_login' %}" method="post">
        {% csrf_token %}
        <label for="username">username:</label>
        <input type="text" name="username" placeholder="Enter Username">
        
        <label for="password">password:</label>
        <input type="password" name="password">

        <input type="submit" value="Login">
    </form>
</div>


{% endblock %}

first_project/templates/user_authentication/registration.html
{% extends "user_authentication/base.html" %}
{% load static %}

{% block body_block %}

<div class="jumbotron">
    {% if registered %}
        <h1>Thank you for registering!</h1>
    {% else %}
        <h1>Register Here!</h1>
        <h3>Fill out the form:</h3>
        <form action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ user_form.as_p }}
            {{ profile_form.as_p}}
            <input type="submit" value="Register">
        </form>
    {% endif %}
</div>

{% endblock %}